name: Code Validation
run-name: ${{ github.actor }} is running the Github Actions 🚀

on: 
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'force-app/**'
    branches:
      - sit

jobs:
  build-and-deploy:
    permissions:
      contents: read
      security-events: write
      actions: read

    runs-on: ubuntu-latest
    environment: sit
    steps:
      - run: echo "This is my first Job"
        name: "First Job Message"
        
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          
      - name: npm install
        run: echo "running npm install"
        
      ## Install Salesforce CLI
      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Install Salesforce Code Analyzer
        run: sf plugins install @salesforce/sfdx-scanner

      - name: Installing the sfdx-git-delta plugin
        id: install-sfdx-delta-plugin
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo 'y' | sf plugins install sfdx-git-delta
          
      - name: Decrypt the server.key.enc file
        run: openssl enc -nosalt -aes-256-cbc -d -in ${{ secrets.ENCRYPTED_KEY_FILE }} -out ${{ secrets.JWT_KEY_FILE }} -base64 -K ${{ secrets.KEY }} -iv ${{ secrets.IV }}

      ## Authorize with Salesforce org -SIT
      - name: Authorize with Salesforce org
        run: sf org login jwt --username ${{ secrets.SF_USERNAME }} --jwt-key-file ${{ secrets.JWT_KEY_FILE }} --client-id ${{ secrets.SF_CLIENT_ID }} --set-default --alias sit --instance-url ${{ secrets.SF_INSTANCE_URL }}

      - name: Generate the package.xml for delta files
        id: generate-delta-files
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          mkdir delta
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output "./delta" --ignore-whitespace -d -i .sgdignore
          echo "--- package.xml generated with added and modified metadata ---"
          cat delta/package/package.xml
          ls delta
          
      ## Identify and Run Tests for Modified Apex Classes
      - name: Run the test coverage for modified classes
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          mkdir -p reports
          # Check if the delta/force-app/main/default/classes directory exists
          if [ -d "delta/force-app/main/default/classes" ]; then
          # Find modified Apex classes from the delta directory
          MODIFIED_CLASSES=$(find delta/force-app/main/default/classes -name '*.cls')
          
          if [ -z "$MODIFIED_CLASSES" ]; then
            echo "No Apex classes modified."
          else
            echo "Modified Apex classes: $MODIFIED_CLASSES"
            
            # Identify related test classes and run them
            TEST_CLASSES=""
            for CLASS_PATH in $MODIFIED_CLASSES; do
              # Extract class name from file path and assume test class naming convention: ClassNameTest.cls
              CLASS_NAME=$(basename $CLASS_PATH .cls)
              TEST_CLASS="${CLASS_NAME}Test"
              
              # Check if the corresponding test class exists
              if [ -f "force-app/main/default/classes/${TEST_CLASS}.cls" ]; then
                TEST_CLASSES="$TEST_CLASSES,$TEST_CLASS"
              fi
            done
            
            # Remove leading comma
            TEST_CLASSES=${TEST_CLASSES#,}
            
            if [ -z "$TEST_CLASSES" ]; then
              echo "No test classes found for modified classes."
              echo "Skipping test execution as no relevant test classes are found."
            else
              echo "Running tests for: $TEST_CLASSES"
              
              # Run tests only for the modified classes
              sf apex run test --class-names $TEST_CLASSES --code-coverage  --target-org Developer --result-format json --output-dir reports/ --wait 30
            fi
            fi
          else
            echo "No modified Apex classes found in the delta. Skipping test execution."
          fi


      
      ## Validate and Deploy only Delta changes to Salesforce SIT Org
      - name: Deploy the code to Salesforce (Validation Only)
        run: |
          if [ -d "delta/force-app" ]; then
            echo "Validating deployment for the changes in the delta directory."
            sf project deploy validate --source-dir delta/force-app --target-org sit
          else
            echo "No changes detected for deployment validation."
          fi

  clean-up:
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    steps:
      - run: echo "This is my second Job"
        name: "Print Message"
